### ISSUE TITLE
App Storeのダウンロードページへのリンクを貼ることの提案

### ISSUE THREAD

**Issue by kokeiro001** [hirothings/qiita-pocket#1]
README.mdまたはリポジトリの(Descriptionの隣りにある)Websiteに、[App Storeのダウンロードページへのリンク](https://itunes.apple.com/jp/app/qiita-pocket-%E3%81%82%E3%81%A8%E3%81%A7%E8%AA%AD%E3%82%80qiita%E3%83%AA%E3%83%BC%E3%83%80%E3%83%BC/id1219758424?l=en&mt=8)を貼るのはいかがでしょうか。

　私は下記ページからこのリポジトリを見つけました。

> [あとで読むQiitaリーダーアプリをリリースしました - Qiita](http://qiita.com/hirothings/items/78493363df04e5f31d25?utm_source=Qiita%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%B9&utm_campaign=f7efd0d380-Qiita_newsletter_258_03_05_2017&utm_medium=email&utm_term=0_e44feaa081-f7efd0d380-33140949)

　私はこの記事でApp Storeに公開されていることを知りましたが、このリポジトリを直接見に来た方はApp Storeで公開されていることを(自分で検索をかけない限り)知ることができません。また、現状ではApp Store上の説明のほうが詳しいです。

　より多くダウンロードしてもらうため、機能を知ってもらうためにリンクを貼るのはいかがでしょうか。それほど手間でもないと思いますので。

---

GitHubにある他のリポジトリが、どのようにApp Storeへのリンクを張っているかの参考URL

> [Search · https://itunes.apple.com/](https://github.com/search?o=desc&q=https%3A%2F%2Fitunes.apple.com%2F&s=stars&type=Repositories&utf8=%E2%9C%93)

**Comment by hirothings** [comment]
@kokeiro001 

対応が遅くなりすみません。
issueありがとうございます。参考URLも大変参考になりました。
readmeとwebsiteを更新しましたので、お手すきでご確認いただけますと幸いです。

**Comment by kokeiro001** [comment]
@hirothings 
確認しました、ありがとうございます！

せっかくいい感じのアプリなのに、説明不足で勿体無いなぁと思い、勢いのままissue立ててしまい、いらぬお節介だったかもしれんとビクビクしてました。

Closeさせていただきます。

**Comment by hirothings** [comment]
いえいえ、1人でやっていたら気を回さずそのままにしている所でした。
ご指摘ありがとうございます！
